import { chromium } from '@playwright/test';
const browser = await chromium.launch({ channel: 'chrome', headless: true });
let page = await browser.newPage({ viewport: { width: 1440, height: 960 } });
page.on('pageerror', e => console.log('PAGE ERROR', e.message));
page.on('console', e => { if (e.type() === 'error') console.log('CONSOLE ERROR', e.text()); });
await page.goto('http://127.0.0.1:5178/?debug');
await page.locator('#start').click();
await page.waitForTimeout(1500);
await page.screenshot({ path: '/private/tmp/drift-desktop.png' });
await page.close();
const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
page = await mobile.newPage();
await page.goto('http://127.0.0.1:5178/?debug');
await page.locator('#start').tap();
await page.waitForTimeout(300);
await page.screenshot({ path: '/private/tmp/drift-mobile.png' });
console.log(await page.evaluate(() => ({ overflow: document.documentElement.scrollWidth > innerWidth, webgl: !!document.querySelector('canvas'), state: window.__drift.sim.telemetry })));
await page.setViewportSize({ width: 844, height: 390 });
await page.waitForTimeout(1000);
await page.screenshot({ path: '/private/tmp/drift-landscape.png' });
await page.setViewportSize({ width: 320, height: 568 });
await page.waitForTimeout(1000);
await page.screenshot({ path: '/private/tmp/drift-small.png' });
await browser.close();
